// Generated by gencpp from file motor_control_pkg/ModbusWriteResponse.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_PKG_MESSAGE_MODBUSWRITERESPONSE_H
#define MOTOR_CONTROL_PKG_MESSAGE_MODBUSWRITERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control_pkg
{
template <class ContainerAllocator>
struct ModbusWriteResponse_
{
  typedef ModbusWriteResponse_<ContainerAllocator> Type;

  ModbusWriteResponse_()
    : success(false)
    , message()  {
    }
  ModbusWriteResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModbusWriteResponse_

typedef ::motor_control_pkg::ModbusWriteResponse_<std::allocator<void> > ModbusWriteResponse;

typedef boost::shared_ptr< ::motor_control_pkg::ModbusWriteResponse > ModbusWriteResponsePtr;
typedef boost::shared_ptr< ::motor_control_pkg::ModbusWriteResponse const> ModbusWriteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator1> & lhs, const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator1> & lhs, const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control_pkg/ModbusWriteResponse";
  }

  static const char* value(const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModbusWriteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control_pkg::ModbusWriteResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_PKG_MESSAGE_MODBUSWRITERESPONSE_H
