// Generated by gencpp from file motor_control_pkg/ModbusWrite.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_PKG_MESSAGE_MODBUSWRITE_H
#define MOTOR_CONTROL_PKG_MESSAGE_MODBUSWRITE_H

#include <ros/service_traits.h>


#include <motor_control_pkg/ModbusWriteRequest.h>
#include <motor_control_pkg/ModbusWriteResponse.h>


namespace motor_control_pkg
{

struct ModbusWrite
{

typedef ModbusWriteRequest Request;
typedef ModbusWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModbusWrite
} // namespace motor_control_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_control_pkg::ModbusWrite > {
  static const char* value()
  {
    return "1d0506667b2278e5081b9ba14a109960";
  }

  static const char* value(const ::motor_control_pkg::ModbusWrite&) { return value(); }
};

template<>
struct DataType< ::motor_control_pkg::ModbusWrite > {
  static const char* value()
  {
    return "motor_control_pkg/ModbusWrite";
  }

  static const char* value(const ::motor_control_pkg::ModbusWrite&) { return value(); }
};


// service_traits::MD5Sum< ::motor_control_pkg::ModbusWriteRequest> should match
// service_traits::MD5Sum< ::motor_control_pkg::ModbusWrite >
template<>
struct MD5Sum< ::motor_control_pkg::ModbusWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_control_pkg::ModbusWrite >::value();
  }
  static const char* value(const ::motor_control_pkg::ModbusWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_control_pkg::ModbusWriteRequest> should match
// service_traits::DataType< ::motor_control_pkg::ModbusWrite >
template<>
struct DataType< ::motor_control_pkg::ModbusWriteRequest>
{
  static const char* value()
  {
    return DataType< ::motor_control_pkg::ModbusWrite >::value();
  }
  static const char* value(const ::motor_control_pkg::ModbusWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_control_pkg::ModbusWriteResponse> should match
// service_traits::MD5Sum< ::motor_control_pkg::ModbusWrite >
template<>
struct MD5Sum< ::motor_control_pkg::ModbusWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_control_pkg::ModbusWrite >::value();
  }
  static const char* value(const ::motor_control_pkg::ModbusWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_control_pkg::ModbusWriteResponse> should match
// service_traits::DataType< ::motor_control_pkg::ModbusWrite >
template<>
struct DataType< ::motor_control_pkg::ModbusWriteResponse>
{
  static const char* value()
  {
    return DataType< ::motor_control_pkg::ModbusWrite >::value();
  }
  static const char* value(const ::motor_control_pkg::ModbusWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_CONTROL_PKG_MESSAGE_MODBUSWRITE_H
